---
- name: Setup Proxmox
  hosts: proxmox
  vars:
    cron_backup_smbshare: "proxmox_sync_proxmox_smb_share_to_onedrive.sh"
  tasks:
    - name: Copy cron file
      ansible.builtin.copy:
        src: "{{ local_crons_folder }}/{{ cron_backup_smbshare }}"
        dest: "/root/crons/{{ cron_backup_smbshare }}"
        mode: "0744"
        backup: false
    - name: Add cron for syncing smb share to onedrive
      ansible.builtin.cron:
        name: "Sync SMB Share to Onedrive cron"
        minute: "23"
        job: "/root/crons/{{ cron_backup_smbshare }}"
        state: absent
