---
galaxy_info:
  author: Abhishek Ranjan
  description: Role to install shell utilities on Debian-based systems
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
dependencies: []
