---
- name: Setup nas
  hosts: prometheus
  # roles:
  #   - git-setup
  #   - debian-shell-utilities
  vars:
    prometheus_backup_cron: "prometheus_backup.sh"
    prometheus_backup_cron_log_dir: "prometheus-backup-cron"

    prometheus_photos_backup_cron: "prometheus_photos_backup.sh"
    prometheus_photos_backup_cron_log_dir: "prometheus-photos-backup-cron"

    cron_dir: "/opt/crons"
    cron_logs_dir: "/var/log/crons"
  tasks:
    # - name: Include ZSH configuration tasks
    # include_tasks: ../tasks/debian-ubuntu-common/zsh-config.yaml
    - name: ZFS configurations
      include_tasks: zfs-config.yaml
    - name: Setup crons
      include_tasks: setup-crons.yaml
# - name: Install python3
#   become: true
#   ansible.builtin.apt:
#     update_cache: false
#         pkg:
#           - python3
#           - python3-dev
#           - python3-pip
#           - python3-setuptools
#           - python3-docker
#     - name: Installing Special Purpose Utilities
#       become: true
#       ansible.builtin.apt:
#         update_cache: no
#         pkg:
#           - aria2
#           - fzf
# - name: Install NodeJS with it's playbook
#   ansible.builtin.import_playbook: setup/setupNasNodejs.yaml

- name: Setup projects
  ansible.builtin.import_playbook: setup-projects-on-prometheus.yaml
