---
- name: Setup nas
  hosts: prometheus
  roles:
    - git-setup
    - debian-shell-utilities
    - debian-install-docker
  tasks:
    - name: Setup folder structure
      include_tasks: setup-folder-structure.yaml
    - name: Include ZSH configuration tasks
      include_tasks: ../tasks/debian-ubuntu-common/zsh-config.yaml
    - name: ZFS configurations
      include_tasks: zfs-config.yaml
    - name: Setup SCSI timeout
      include_tasks:
        file: setup-scsi-timeout.yaml
        apply:
          tags: scsi
      tags: scsi
    - name: Setup Docker Networks
      include_tasks: setup-docker-networks.yaml
    - name: Setup crons
      include_tasks: setup-crons.yaml
    - name: Installing Special Purpose Utilities
      become: true
      ansible.builtin.apt:
        pkg:
          - aria2
    - name: Setup karakeep
      include_tasks: setup-karakeep.yaml
- name: Start docker containers from compose files
  import_playbook: start-docker-containers.yaml
- name: Setup projects
  ansible.builtin.import_playbook: setup-projects-on-prometheus.yaml
- name: Setup Home Assistant
  ansible.builtin.import_playbook: setup-homeassistant.yaml
