---
# tasks file for debian-shell-utilities
- name: Installing Ubuntu/Debian Utilities
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - wget
      - curl
      - iperf3
      - p7zip-full
      - htop
      - iputils-ping
      - gnupg
      - cron
      - git
      - python3
      - python3-setuptools
- name: Installing utils for better shell - zsh,tmux
  become: true
  ansible.builtin.apt:
    pkg:
      - tmux
      - zsh
- name: Install useful CLI tools
  become: true
  ansible.builtin.apt:
    pkg: "{{ item.name }}"
  loop:
    - { name: "micro", desc: "micro - terminal text editor" }
    - { name: "mc", desc: "midnight commander(mc) - terminal file explorer" }
    - { name: "fzf", desc: "fzf - fuzzy finder" }
    - { name: "zoxide", desc: "zoxide" }
    - { name: "ncdu", desc: "ncdu - disk usage analyzer" }
  loop_control:
    label: "{{ item.desc }}"
