---
prometheus_user: "abhi"
prometheus_group: "abhi"

prometheus_compose_dir: "/zfspool/containers"
prometheus_docker_volumes_dir: "/zfspool/docker-volumes"

prometheus_backup_cron: "prometheus_backup.sh"
prometheus_backup_cron_log_dir: "prometheus-backup-cron"

prometheus_backup_sync_onedrive_cron: "prometheus_backup_sync_onedrive.sh"
prometheus_backup_sync_onedrive_cron_log_dir: "prometheus-backup-sync-onedrive-cron"

prometheus_photos_backup_cron: "prometheus_photos_backup.sh"
prometheus_photos_backup_cron_log_dir: "prometheus-photos-backup-cron"

prometheus_photos_backup_sync_onedrive_cron: "prometheus_photos_backup_sync_onedrive.sh"
prometheus_photos_backup_sync_onedrive_cron_log_dir: "prometheus-photos-backup-sync-onedrive-cron"

cron_dir: "/opt/crons"
cron_logs_dir: "/var/log/crons"
