---
- name: Start Expense Category Predictor
  hosts: nas
  vars:
    expense_category_predictor_dest: "{{ nas_projects_folder }}/expenseCategoryPredictor"
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:
    - name: Include expense category predictor setup tasks
      ansible.builtin.include_tasks: ../../projects/tasks/setup-expense-category-predictor.yaml
