---
- name: "Ensure cron and related directories exist"
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "{{ atlas_crons_folder }}"
    - "{{ atlas_cron_logs_dir }}"
    - "{{ atlas_cron_logs_dir }}/{{ atlas_backup_cron_log_dir }}"
    - "{{ atlas_cron_logs_dir }}/{{ atlas_backup_sync_onedrive_cron_log_dir }}"
- name: Copy cron files
  ansible.builtin.copy:
    src: "{{ local_crons_folder }}/{{ item.script }}"
    dest: "{{ atlas_crons_folder }}/{{ item.script }}"
    mode: "0744"
    backup: false
  loop:
    - { name: "Atlas backup cron", script: "{{ atlas_backup_cron }}" }
    - {
        name: "Atlas backup sync onedrive cron",
        script: "{{ atlas_backup_sync_onedrive_cron }}",
      }
- name: Add cron job to crontab
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    job: >
      {{ atlas_crons_folder }}/{{ item.script }} 2>&1 |
      tee -a {{ atlas_cron_logs_dir }}/{{ item.log_dir }}/$(date +\%Y-\%m-\%d_\%H-\%M-\%S).log |
      systemd-cat -t "{{ item.name }}"
    state: present
  loop:
    - {
        name: "Atlas backup cron",
        minute: "10",
        script: "{{ atlas_backup_cron }}",
        log_dir: "{{ atlas_backup_cron_log_dir }}",
      }
    - {
        name: "Atlas backup sync onedrive cron",
        minute: "15",
        script: "{{ atlas_backup_sync_onedrive_cron }}",
        log_dir: "{{ atlas_backup_sync_onedrive_cron_log_dir }}",
      }
